services:
  traefik:
    image: ghcr.io/traefik/traefik:3.3
    container_name: ${BASE_CONTAINER_NAME}traefik
    restart: on-failure
    command:
      - --ping=true
      - --api.insecure=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.constraints=Label(`traefik.${BASE_CONTAINER_NAME}`,`true`)
      - --entrypoints.web.address=:80
      - --experimental.plugins.rewrite-body.modulename=github.com/packruler/rewrite-body
      - --experimental.plugins.rewrite-body.version=v1.2.0
      - --experimental.plugins.rewriteHeaders.modulename=github.com/XciD/traefik-plugin-rewrite-headers
      - --experimental.plugins.rewriteHeaders.version=v0.0.3
    ports:
      - "${EXTERNAL_HTTP_PORT}:80"
      - "${EXTERNAL_TRAEFIK_MANAGEMENT_PORT}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    extra_hosts:
      - host.docker.internal:172.17.0.1
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      retries: 10

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${BASE_CONTAINER_NAME}homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
      - HOMEPAGE_VAR_TITLE=${HOMEPAGE_VAR_TITLE}
      - HOMEPAGE_VAR_SEARCH_PROVIDER=${HOMEPAGE_VAR_SEARCH_PROVIDER}
      - HOMEPAGE_VAR_HEADER_STYLE=${HOMEPAGE_VAR_HEADER_STYLE}
      - HOMEPAGE_VAR_WEATHER_CITY=${HOMEPAGE_VAR_WEATHER_CITY}
      - HOMEPAGE_VAR_WEATHER_LAT=${HOMEPAGE_VAR_WEATHER_LAT}
      - HOMEPAGE_VAR_WEATHER_LONG=${HOMEPAGE_VAR_WEATHER_LONG}
      - HOMEPAGE_VAR_WEATHER_TIME=${TIMEZONE}
      - HOMEPAGE_VAR_WEATHER_UNIT=${HOMEPAGE_VAR_WEATHER_UNIT}
    volumes:
      - ${CONFIG_ROOT:-.}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_ROOT}:/data
    restart: on-failure
    command:
      [node, server.js]
    labels:
      - traefik.${BASE_CONTAINER_NAME}=true
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=(PathPrefix(`/`))
      - traefik.http.services.homepage.loadbalancer.server.port=3000

  watchtower:
    image: ghcr.io/containrrr/watchtower:latest
    container_name: ${BASE_CONTAINER_NAME}watchtower
    restart: on-failure
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: ${BASE_CONTAINER_NAME}autoheal
    restart: on-failure
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Include media compose file
include:
  - media-compose/docker-compose.media.yml

networks:
  default:
    name: raven-compose-net
