---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: {{HOMEPAGE_VAR_TITLE}}

headerStyle: underlined

layout:
  Media:
    style: row
    columns: 3
  Media Download:
    style: row
    columns: 3
  A.I Services:
    style: row
    columns: 3

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
